#!/usr/bin/env bash
#
#  botcoind The botcoin more server.
#
#
# chkconfig: 345 80 20
# description: botcoind
# processname: botcoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/botcoind, see below
if [ -f /etc/sysconfig/botcoind ]; then
        . /etc/sysconfig/botcoind
fi

RETVAL=0

prog=botcoind
# you can override the lockfile via BLACKMORED_LOCKFILE in /etc/sysconfig/botcoind
lockfile=${BLACKMORED_LOCKFILE-/var/lock/subsys/botcoind}

# botcoind defaults to /usr/bin/botcoind, override with BLACKMORED_BIN
botcoind=${BLACKMORED_BIN-/usr/bin/botcoind}

# botcoind opts default to -disablewallet, override with BLACKMORED_OPTS
botcoind_opts=${BLACKMORED_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $bitcoind $bitcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
